### ISSUE TITLE
Extended class ZendeskConfig defines it as instance member property

### ISSUE THREAD

**Issue by basil2style** [AlisonVilela/ngx-zendesk-webwidget#1]
Hi @AlisonVilela ,
 I am getting the following error on app.module.ts file,
`Class 'ngxZendeskWebwidgetConfig' defines instance member function 'beforePageLoad', but extended class 'ZendeskConfig' defines it as instance member property.`

especially when declaring the `export class ZendeskConfig extends ngxZendeskWebwidgetConfig `
Please help
-Basil

**Comment by pfrendo** [comment]
Try this

```
export class ZendeskConfig extends ngxZendeskWebwidgetConfig {

	accountUrl = "viks.zendesk.com";
	beforePageLoad(zE: any) {
		zE.setLocale("en");
		zE.hide();
	}

}

ngxZendeskWebwidgetModule.forRoot(ZendeskConfig),
```

**Comment by AlisonVilela** [comment]
@basil2style Were you able to solve your problem?

**Comment by lud42** [comment]
The answer from pfrendo is good, thanks

The readme needs an update :)

**Comment by shekhartupe** [comment]
@lud42, so you got this working for you? I am facing issue beyond this reported here as #3. If you can guide?

**Comment by AlisonVilela** [comment]
@lud42 This is already explained in readme

**Comment by AlisonVilela** [comment]
@shekhartupe How are you implementing it?

**Comment by shekhartupe** [comment]
@AlisonVilela I have updated issue #3 with the code for the issue. Please help.

**Comment by shekhartupe** [comment]
I guess this is also README update and can be closed. @lud42 @basil2style @AlisonVilela
