### ISSUE TITLE
Update for angular 6

### ISSUE THREAD

**Issue by xaolas** [AlisonVilela/ngx-zendesk-webwidget#11]
warning " > ngx-zendesk-webwidget@0.1.3" has incorrect peer dependency "@angular/core@^5.2.1".
warning " > ngx-zendesk-webwidget@0.1.3" has incorrect peer dependency "rxjs@^5.5.6".

Please up Angular and rxjs versions

**Comment by mackelito** [comment]
We are running angular 7.0.2 and do not have these warnings

**Comment by pegaltier** [comment]
Please use the last version of the lib: 0.1.4

**Comment by mackelito** [comment]
For anyone who want's to give it a try.. I have create a fork and published it here https://www.npmjs.com/package/ng-zendesk-webwidget
