### ISSUE TITLE
How to hide the help button

### ISSUE THREAD

**Issue by beany-vu** [AlisonVilela/ngx-zendesk-webwidget#15]
I want to hide the help button and use the other button for triggering the button. I tried with the hide() but it doesn't help. I don't know if it's possible with the module?

**Comment by shekhartupe** [comment]
Yes it possible. I am doing it with

export class ZendeskConfig extends ngxZendeskWebwidgetConfig {
  accountUrl = 'xxxxxxxx.zendesk.com';
  beforePageLoad(zE) {
    zE.setLocale('en');
    zE.hide();
  };
}

And then have an action to show the widget.

**Comment by beany-vu** [comment]
it seems still show the launcher (http://prntscr.com/keig3l). Is it possible for me to hide the button and use the other for triggering the widget?

**Comment by shekhartupe** [comment]
Will need to see your code to know more.
Attached sample program emulating this implementation.
[zendesk-integration-app.zip](https://github.com/AlisonVilela/ngx-zendesk-webwidget/files/2259770/zendesk-integration-app.zip)
