### ISSUE TITLE
Button not showing on iOS

### ISSUE THREAD

**Issue by zimnerd** [AlisonVilela/ngx-zendesk-webwidget#16]
Hi,

Thanks for this amazing plugin. I have used it in ionic 3 project and it shows well on android but on ios it doesnt show the icon.

Thanks

**Comment by zimnerd** [comment]
Solved it by adding  <allow-navigation href="*" /> in the config.xml to allow href="about:blank"

**Comment by mackelito** [comment]
@zimnerd so this can be closed then?

**Comment by cassini-usman** [comment]
@zimnerd i added `<allow-intent href="about:blank" />` in config.xml but it's still not working

**Comment by zimnerd** [comment]
> @zimnerd i added `<allow-intent href="about:blank" />` in config.xml but it's still not working. How did you make it work?

Hi @cassini-usman  I don't have my laptop with me, Please try to add to <allow-navigation  href="about:blank"  /> and see if that will solve the issue

**Comment by zimnerd** [comment]
> @zimnerd i added `<allow-intent href="about:blank" />` in config.xml but it's still not working. How did you make it work?

Try `<allow-navigation href="about:blank" />  `

**Comment by zimnerd** [comment]
> @zimnerd so this can be closed then?

Yes.

**Comment by acantore** [comment]
I think @cassini-usman is reporting a view problem.
Header buttons are hidden behind the status bar.
Am I correct?

**Comment by EOussama** [comment]
Nothing here worked for me.

**Comment by mackelito** [comment]
@EOussama Now I'm not actively updating this fork https://github.com/mackelito/ngx-zendesk-webwidget (the company where I used it no loger exists 😢) but you could give it a try and see if it works for you!

**Comment by EOussama** [comment]
@mackelito, thank you for your response man, it meant a lot, although I have already figured out a workaround for this problem.
I added the following snippet in `config.xml`

```xml
<platform name="ios">
    <allow-intent href="*" />
    <allow-navigation href="*" />
</platform>
```

**Comment by mackelito** [comment]
Great to hear that you solved it! :)
