### ISSUE TITLE
Add Support for Angular 7

### ISSUE THREAD

**Issue by levz0r** [AlisonVilela/ngx-zendesk-webwidget#20]
Currently it is not possible to update to Angular 7 because

`Package "ngx-zendesk-webwidget" has an incompatible peer dependency to "rxjs" (requires "^5.5.6", would install "6.3.3").`

**Comment by mackelito** [comment]
warning " > ngx-zendesk-webwidget@0.1.4" has incorrect peer dependency "@angular/core@6.0.0".
warning " > ngx-zendesk-webwidget@0.1.4" has incorrect peer dependency "rxjs@6.0.0".
warning " > ngx-zendesk-webwidget@0.1.4" has incorrect peer dependency "zone.js@0.8.20".

**Comment by mackelito** [comment]
Any updates?

**Comment by mackelito** [comment]
@levz0r feel free to test this out https://www.npmjs.com/package/ng-zendesk-webwidget
(a updated fork)

**Comment by sriten** [comment]
Awesome! Thanks for this update. I'm going to test it out now. Also, I believe there's a chance to update Zendesk API to use v2 rather than v1. Is there any reason why v2 is not used??

**Comment by mackelito** [comment]
Right now I was just focused to get it out with proper deeps.. perhaps later! :)
