### ISSUE TITLE
Error 404 https://ekr.zdassets.com/compose/web_widget/

### ISSUE THREAD

**Issue by HelySaul** [AlisonVilela/ngx-zendesk-webwidget#24]
I just can't use the widget 'cause this page doesn't load 'https://ekr.zdassets.com/compose/web_widget/'

**Comment by lizardi21** [comment]
Hello!

I had the same error. On the panel, I changed my Chat status: Invisible -> Connected.

https://[YourDomain].zendesk.com/chat/agent#home

**Comment by mackelito** [comment]
Feel free to try out my fork https://github.com/mackelito/ng-zendesk-webwidget
Will try to keep it more alive than this repo
