### ISSUE TITLE
Angular 8 build failed when using ngx-zendesk-webwidget-8

### ISSUE THREAD

**Issue by ahmedMovin** [AlisonVilela/ngx-zendesk-webwidget#35]
I tried to to use zendesk into my angular 8 project by using the plugin ngx-zendesk-webwidget-8.
but during the build I have the following error : 
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-zendesk-webwidget' in '/Users/ahmed/Developer/movinmotion/talents-frontend/src/app'
Thanks in advance

**Comment by AlisonVilela** [comment]
I have nothing to do with this plugin, use the plugin [ngx-zendesk-webwidget](https://www.npmjs.com/package/ngx-zendesk-webwidget) because it's the most up to date

**Comment by AlisonVilela** [comment]
Someone deployed to NPM using a fork and didn't change things about my repository

**Comment by Prorock201** [comment]
Could you provide an example, because the example in REAME doen't work (I've got an error `this._NgxZendeskWebwidgetService.zE is not a function`)

**Comment by AlisonVilela** [comment]
If you are using another project it will not work anyway, this ngx-zendesk-webwidget-8 is not mine

**Comment by Craby-Patty** [comment]
I am also getting the error (with your package)
`   this._NgxZendeskWebwidgetService.zE is not a function)`
The only thing in my constructor is 
`    this._NgxZendeskWebwidgetService.zE('webWidget', 'show');`
The importing seems to be working fine

**Comment by AlisonVilela** [comment]
Are you using the correct repo? ngx-zendesk-webwidget-8 is not mine
Show me which package you are using in your package.json

**Comment by AlisonVilela** [comment]
Can you reproduce this error?

**Comment by gcstarke** [comment]
> I am also getting the error (with your package)
> ` this._NgxZendeskWebwidgetService.zE is not a function)`
> The only thing in my constructor is
> ` this._NgxZendeskWebwidgetService.zE('webWidget', 'show');`
> The importing seems to be working fine

@Craby-Patty 

I had the same error. Be sure to install the correct version for your specific version of Angular. For example, I'm running Angular 6.1.10 and I had to install npm i ngx-zendesk-webwidget@0.1.4 and follow these instructions. [https://www.npmjs.com/package/ngx-zendesk-webwidget/v/0.1.4](url)

**Comment by AlisonVilela** [comment]
The use of the zE function was added only in version V2.0.0
```API services that used legacy zE methods (setLocale, identify, hide, show, activate, setHelpCenterSuggestions, setSettings) have been removed, you now need to use the new command syntax for greater flexibility (breaking changes)```

**Comment by AlisonVilela** [comment]
For V0.1.4 use `setLocale`, `identify`, `hide`, `show`, `activate`, `setHelpCenterSuggestions`, `setSettings`, but this is a legacy, would you update your packages

**Comment by Craby-Patty** [comment]
Thanx, I managed to get it working

**Comment by stockcj** [comment]
> 
> 
> Thanx, I managed to get it working

How did you manage to get it working? I've got the same issue. Using Angular 8 and version 2.1.1:
this._NgxZendeskWebwidgetService.zE is not a function

**Comment by AlisonVilela** [comment]
ngx-zendesk-webwidget-8 is not mine

**Comment by stockcj** [comment]
> 
> 
> ngx-zendesk-webwidget-8 is not mine

My issue occurs on ngx-zendesk-webwidget. Sorry, perhaps I should create a new issue?
