### ISSUE TITLE
Toggling Widget

### ISSUE THREAD

**Issue by diomededavid** [AlisonVilela/ngx-zendesk-webwidget#39]
Thank you for making this. This is not an issue as it is more of a question. How would you toggle the widget with a button?

My current logic looks like below. I can toggle widget off but cannot toggle back on. 

```
isZen = false;

toggleZen() {
   if (this.isZen) {
     this._NgxZendeskWebWidgetService.zE('webWidget', 'show');
   } else {
     this._NgxZendeskWebWidgetService.zE('webWidget', 'hide');
   }
  }```

**Comment by AlisonVilela** [comment]
Sorry for the delay

I think you already solved the problem, but did you try something like that?

 ```
 isZenOpen = false;
 
 toggleZen() {
    if (!this.isZenOpen) {
      this._NgxZendeskWebWidgetService.zE('webWidget', 'show');
      this.isZenOpen = true;
    } else {
      this._NgxZendeskWebWidgetService.zE('webWidget', 'hide');
      this.isZenOpen = false;
    }
 }
 ```

> Thank you for making this. This is not an issue as it is more of a question. How would you toggle the widget with a button?
> 
> My current logic looks like below. I can toggle widget off but cannot toggle back on.
> 
> ```
> isZen = false;
> 
> toggleZen() {
>    if (this.isZen) {
>      this._NgxZendeskWebWidgetService.zE('webWidget', 'show');
>    } else {
>      this._NgxZendeskWebWidgetService.zE('webWidget', 'hide');
>    }
>   }```
> ```

**Comment by diomededavid** [comment]
I will try it. Thank you.
