### ISSUE TITLE
Enable visitor authentication support

### ISSUE THREAD

**Issue by sumit98788** [AlisonVilela/ngx-zendesk-webwidget#45]
Does this package support the visitor authentication settings (https://developer.zendesk.com/embeddables/docs/widget/settings#authenticate)

<script type="text/javascript">
  window.zESettings = {
    webWidget: {
      authenticate: {
        chat: {
          jwtFn: function(callback) {
            // Fetch your jwt token and then call our supplied callback below.
            callback('YOUR_JWT_TOKEN');
          }
        }
      }
    }
  };
</script>

**Comment by sumit98788** [comment]
@AlisonVilela the package seamlessly integrates with zendesk chat in angular app. Thank you for that.
Any insights on visitor authentication (core widget settings) will be very helpful

**Comment by AlisonVilela** [comment]
I don't have time to maintain the repository often, if you can update the documentation and do a PR I would be very appreciative!
