### ISSUE TITLE
Is it possible to set the offset of button and window?

### ISSUE THREAD

**Issue by avelinocneto** [AlisonVilela/ngx-zendesk-webwidget#46]
Is it possible to set the offset of button and window?

**Comment by bonomiandreia** [comment]
I have the same question.

**Comment by AlisonVilela** [comment]
Yeah, it is possible!

`zE('webWidget', 'updateSettings', {
   webWidget: {
      position: { horizontal: 'left', vertical: 'top' }
    }
  }`
