### ISSUE TITLE
[v3.0.1] Cannot find module 'ngx-zendesk-webwidget' or its corresponding type declarations.

### ISSUE THREAD

**Issue by bmartinson** [AlisonVilela/ngx-zendesk-webwidget#49]
When attempting to import any previously defined library file, like the module, I receive a `Cannot find module 'ngx-zendesk-webwidget' or its corresponding type declarations.` with v3.0.0+ despite the fact that the module is indeed installed. I am attempting the import in the same way as I have done in the past and as is recommended based on the docs.

```typescript
import { NgxZendeskWebwidgetModule } from 'ngx-zendesk-webwidget';
// ...
```

The public-api.ts file looks correct to me. and there don't seem to be any breaking changes in terms of naming. Not exactly sure why the module isn't accessible. Thoughts?

**Comment by AlisonVilela** [comment]
Hi @bmartinson , can you reproduce this error in an example code? I tested a lot here and didn't find this error scenario

**Comment by bmartinson** [comment]
Hi @AlisonVilela, thanks for the quick response. Check out this StackBlitz sample app that attempts to use the package. I see the same error in this case as well.

https://stackblitz.com/edit/angular-ivy-mph8na?file=src/app/app.module.ts

**Comment by 8odoris** [comment]
I have the same issue. `Cannot find module 'ngx-zendesk-webwidget' or its corresponding type declarations.`

Adding the full path (ngx-zendesk-webwidget/src/lib/...) should be a solution but I don't think that is the proper one.

**Comment by AlisonVilela** [comment]
I found my mistake, I will fix it and deploy a new version

**Comment by AlisonVilela** [comment]
I deployed version 3.0.2 which fixes this problem!

**Comment by bmartinson** [comment]
Awesome, thanks a bunch @AlisonVilela!
