### ISSUE TITLE
_ngxZendeskWebwidgetService.show() is undefined 

### ISSUE THREAD

**Issue by Heenash04** [AlisonVilela/ngx-zendesk-webwidget#6]
Can you please tell me how to resolve this issue

**Comment by AlisonVilela** [comment]
Tell us how you configured the module

**Comment by AlisonVilela** [comment]
What is the version of the component and the Angular?

**Comment by hindusta** [comment]
Angular version - 4.3.4

**Comment by AlisonVilela** [comment]
Try use 0.1.2 of component

**Comment by hindusta** [comment]
Sorry for the Confusion I am using Angular 5.2.1 version and Component version is 0.1.3 .Also setSettings is not working

**Comment by AlisonVilela** [comment]
Can you reproduce this error in a new project and send to me?
