### ISSUE TITLE
setSettings is not working

### ISSUE THREAD

**Issue by hindusta** [AlisonVilela/ngx-zendesk-webwidget#7]
export class ZendeskConfig extends ngxZendeskWebwidgetConfig {
  accountUrl = 'peersview.zendesk.com';
  beforePageLoad(zE) {
    zE.setLocale('en');
    zE.hide();
  }

 setSettings = {
  webWidget: {
    contactForm: {
      attachments: false
    }
  }
 }
}

**Comment by lewisames** [comment]
According to the ZenDesk docs, the settings need to be configured before launching the widget.  I found this worked for me.  Just make the call to window.zESettings in your config file, and this will get called before the widget loads

```
import {ngxZendeskWebwidgetConfig} from 'ngx-zendesk-webwidget';

window['zESettings'] = {
  webWidget: {
    chat: {
      suppress: true
    },
    contactOptions: {
      enabled: true,
      contactButton: { '*': 'Get in touch' }
    },
    color: { theme: '#78a300' }
  }
};

export class ZendeskConfig extends ngxZendeskWebwidgetConfig {
  accountUrl = 'url.zendesk.com';
  beforePageLoad(zE) {
    zE.setLocale('en');
    zE.hide();
  }
}
```

**Comment by JeremyLopez** [comment]
@lewisames do you think you can post how you accomplished this, with filenames?  I can't seem to get my settings to do anything.

**Comment by lewisames** [comment]
Sure, the code above the full contents of a file called `app.zendesk.confg.`

This is the relevant pieces of my AppModule
```
import {ZendeskConfig} from './app.zendesk.config';
@NgModule({
    declarations: [...],
    imports:      [
      ngxZendeskWebwidgetModule.forRoot(ZendeskConfig)
    ],
    providers: [...],
  bootstrap: [MainAppShell],
})
export class AppModule {}
```

**Comment by lewisames** [comment]
No @JeremyLopez, I did not.  It didn't really fit our workflow.

**Comment by andrevmc** [comment]
The setSettings (settings) method is not setting window.zESettings. Is this a bug?

**Comment by mackelito** [comment]
@andrevmc tryout https://github.com/mackelito/ng-zendesk-webwidget
