### ISSUE TITLE
Cannot read property button of undefined

### ISSUE THREAD

**Issue by shariajoe** [AlisonVilela/ngx-zendesk-webwidget#8]
**Getting the following error when calling _ngxZendeskWebwidgetService.show()**

TypeError: Cannot read property 'button' of undefined↵    at https://assets.zendesk.com/embeddable_framework/main.js:1:1459986↵    at p (https://v2.zopim.com/bin/v/widget_v2.234.js:12421:3)↵    at Object.h [as handleDelayed] (https://v2.zopim.com/bin/v/widget_v2.234.js:12416:51)↵    at T (https://v2.zopim.com/bin/v/widget_v2.234.js:38029:4)↵    at Object.n [as init] (https://v2.zopim.com/bin/v/widget_v2.234.js:37677:1)↵    at new n (https://v2.zopim.com/bin/v/widget_v2.234.js:814:3)↵    at https://v2.zopim.com/bin/v/widget_v2.234.js:85:1↵    at a (https://v2.zopim.com/bin/v/widget_v2.234.js:344:10)↵    at Object.r [as runAfterFirstChildReady] (https://v2.zopim.com/bin/v/widget_v2.234.js:338:1)↵    at https://v2.zopim.com/bin/v/widget_v2.234.js:84:3

Using lazy loading in angular please confirm that this works with lazy loading.

**Comment by mackelito** [comment]
I can confirm that it works with lazy loading.. using it on our lazy modules

**Comment by shariajoe** [comment]
Sorry should have closed this. Thank you...but perhaps a mention on performance. I don't know if it is my side or adding the widget lowers performance of my site by a significant much.

**Comment by mackelito** [comment]
Hard to tell.. in what way does it lower performance?
How do you notice it?

**Comment by shariajoe** [comment]
I used Chrome's audit tool, ran an audit without the widget, the score on performance went up perhaps you can try that on your side and share insights
