### ISSUE TITLE
Error: Missing accountUrl

### ISSUE THREAD

**Issue by cedricve** [AlisonVilela/ngx-zendesk-webwidget#9]
Getting following error with Angular 5

      ERROR Error: Uncaught (in promise): Error: Missing accountUrl. Please set in app config via ZendeskWidgetProvider

**Comment by ElzioJunior** [comment]
+1

**Comment by shekhartupe** [comment]
Could it be related to https://github.com/AlisonVilela/ngx-zendesk-webwidget/issues/3 ?
